name: MSVC
on:
  push:
    branches: [ master, donation-patch ]
  pull_request:
    branches: [ master, donation-patch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
#     - name: Setup VS2019
#       uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: deps
      run: | 
        git clone https://github.com/xmrig/xmrig-deps c:\xmrig-deps
    
    - name: build
      run: |
        mkdir build && cd build
        cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS=c:\xmrig-deps\msvc2019\x64
        cmake --build . --config Release
        7z a release-win-msvc.zip Release
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: artifact # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: build/release-win-msvc.zip
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: warn # optional, default is warn
        retention-days: 90
      
    - name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
        file: build/release-win-msvc.zip
        draft: true # optional, default is true
        prerelease: false # optional, default is false
        verbose: true # optional, default is false
        # If try to update latest release.
        update_latest_release: true # optional, default is false
        # Set release id to update.If release_id is set, this step will fail if we can not find it.


